version: '2'

services:

  mongodb:
    image: mongo
    ports:
      - "27018:27018"
    volumes:
      - ./dbdata:/data/db
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=development
  app:
    image: node:10
    command: /bin/bash -c "yarn install && npm run dev"
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongodb/gmailpush
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - redis
